import React, { useState } from 'react';
import { ArrowUpRight, Loader2 } from 'lucide-react';
import { streamCustomLlmChat } from '../services/api';
const prompts = ["How does Agora's conversational AI engine compare to OpenAI Realtime?", 'We are evaluating, but $699/month seems expensive compared to DIY.', 'Can you schedule a live 30-minute demo for our engineering team tomorrow at 2 PM?', 'What is your latency SLA and do you handle real-time barge-in?'];
export const SandboxTester: React.FC<{ channelName: string }> = ({ channelName }) => {
  const [input, setInput] = useState(''); const [isStreaming, setIsStreaming] = useState(false); const [output, setOutput] = useState(''); const [question, setQuestion] = useState('');
  const send = async (value = input) => { if (!value.trim() || isStreaming) return; setQuestion(value); setOutput(''); setIsStreaming(true); try { await streamCustomLlmChat(channelName, [{ role: 'user', content: value }], chunk => setOutput(prev => prev + chunk)); } catch (e: any) { setOutput(`Unable to reach Lively: ${e.message}`); } finally { setInput(''); setIsStreaming(false); } };
  return <section className="border-t hairline pt-8"><div className="flex flex-wrap items-end justify-between gap-3 border-b hairline pb-4"><div><p className="editorial-mono text-[10px] uppercase tracking-[.16em] text-[#696862]">04 / Brain playground</p><h2 className="editorial-serif mt-2 text-3xl">Try a thought in the room.</h2><p className="mt-2 text-sm text-[#696862]">Test how Lively responds to buyer questions, objections, and conversation events.</p></div><span className="editorial-mono text-[10px] uppercase tracking-[.14em] text-[#77756e]">Direct LLM test</span></div>
    <div className="mt-5 divide-y hairline border-y hairline">{prompts.map((prompt, i) => <button key={prompt} onClick={() => send(prompt)} disabled={isStreaming} className="flex w-full items-center gap-4 px-2 py-4 text-left text-sm text-[#3c3b37] transition hover:bg-[#ecebe6] disabled:opacity-50"><span className="editorial-mono text-[10px] text-[#6166cf]">0{i + 1}</span><span className="flex-1">{prompt}</span><ArrowUpRight size={15} className="text-[#77756e]"/></button>)}</div>
    <div className="mt-5 flex border-b border-[#77756e]"><input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} disabled={isStreaming} placeholder="Ask Lively something…" className="min-w-0 flex-1 bg-transparent px-1 py-4 text-sm outline-none placeholder:text-[#918f87]"/><button onClick={() => send()} disabled={isStreaming || !input.trim()} className="editorial-mono inline-flex items-center gap-2 px-3 text-[11px] uppercase tracking-[.12em] disabled:opacity-40">{isStreaming && <Loader2 size={13} className="animate-spin"/>} Send <ArrowUpRight size={14}/></button></div>
    {output && <article className="mt-7 border-l-2 border-[#6166cf] pl-5"><p className="editorial-mono text-[10px] uppercase tracking-[.14em] text-[#77756e]">Buyer</p><p className="mt-1 text-sm leading-6 text-[#4c4b46]">“{question}”</p><p className="editorial-mono mt-5 text-[10px] uppercase tracking-[.14em] text-[#6166cf]">Lively</p><p className="mt-1 max-w-3xl whitespace-pre-wrap text-sm leading-7 text-[#292927]">{output}</p><div className="editorial-mono mt-4 flex gap-5 text-[9px] uppercase tracking-[.11em] text-[#77756e]"><span>Retrieval / live</span><span>Deal state / active</span><span>Channel / {channelName}</span></div></article>}
  </section>;
};
